### ISSUE TITLE
Crash with Custom Traits and Potion Core

### ISSUE THREAD

**Issue by mxnmnm** [The-Acronym-Coders/ContentTweaker#189]
Not sure who's at fault but I figured I would report it here because I made the trait using content tweaker.  

here's the trait: https://pastebin.com/GmWdHPVJ
here's the crash report: https://paste.dimdev.org/waqisekucu.mccrash

**Comment by SkySom** [comment]
I'm going to guess that your potion bracket is null. If that's in a CoT loader script it's cause they don't exist yet.

**Comment by kindlich** [comment]
I'd rather think either target or attacker is null, but in any case, you could check using `isNull(attacker)` for example.

SkySom 
If what you said where true he'd gotten a warning in his CrT log about not being able to resolve the bracket (which may be true, since he did not include his CrT log)

But since the Bracket handler is nothing but a method call and this function is executed during the game I don't think that's the cause (unless he misspelled the bracket)
