### ISSUE TITLE
[1.15] Non-full model blocks give an "X-Ray" effect when placed (See included picture)

### ISSUE THREAD

**Issue by Spearkiller** [The-Acronym-Coders/ContentTweaker#213]
https://i.imgur.com/weRlmXm.png

There seems to be no way at the moment to tell a block that it is "notSolid()" resulting in non-solid blocks like my above machine frames removing the texture of the blocks they're touching, giving a both cheaty and ugly "xray" effect.

**Comment by kindlich** [comment]
Hey there,

I added a `.notSolid()` function to the BlockBuilder.
So you can now do
```zenscript
new BlockBuilder()
    .notSolid()
    .build("non_solid_block");
```

Here you can see an image without (left) and with (right) that call.
Since I'm not good with models I just used the MC ones for my tests.

![image](https://user-images.githubusercontent.com/10351787/90175366-978b7f00-dda7-11ea-80fe-bb034380063a.png)


It's the version that ends on `1.15-1.0.0.develop.18.jar`
You can find the version here (once it's been approved).
<https://www.curseforge.com/minecraft/mc-mods/contenttweaker/files/3031468>

You will need the latest CrT beta (.39) for this to work, since I updated some things to properly use CrT's internals.
You can find it here (my Curse launcher didn't even show it to me
<https://www.curseforge.com/minecraft/mc-mods/crafttweaker/files/3031013>


Please leave some feedback if that works for you.

**Comment by Spearkiller** [comment]
Absolutely brilliant, works like a charm!
https://i.imgur.com/7vmrnHX.png

Thank you so much!
