### ISSUE TITLE
unable to create file system contentweaker:ass?

### ISSUE THREAD

**Issue by 435THz** [The-Acronym-Coders/ContentTweaker#264]
I tried creating some standard items, but the mod didn't like that. The game worked fine up until when it recognized my script as valid. Then it started failing on startup.

the crash report: https://pastebin.com/SMYBc0rh
my script: https://pastebin.com/pNttATxG

disabling the script gets rid of the issue, but since all i did was follow the example files, i'm kind of at a loss regarding what i might have done wrong

**Comment by PyroBurnem** [comment]
might it be because you are referencing an item that is yet to be made in the line where you create the creative tab?

edit: understanding more about the 1.18 syntax now, what you'd want for the bracket in line 6 should be `<reference:item:contenttweaker:science_pack_1>` to target the yet-to-be-made item

**Comment by 435THz** [comment]
Yeah no it turns out it was just an outdated version
fixed, i guess
